Prevent double call on token refreshment
lejard-h/chopper pull request #276
Opened 2021-07-22 10:45 UTC by JEuler

There is double processing when you've got your authenticator call. It leads to exceptions like "BuiltList<YourType> is not a String" or something. 

https://github.com/lejard-h/chopper/issues/259 contains the same behavior description.

2021-09-23 08:46 UTC, stewemetal requested changes

2021-09-23 08:46 UTC, stewemetal commented on chopper/lib/src/base.dart
> +  /// Utitlity method to shrink duplicated code (interceptors processing)
I think this comment is unnecessary. 😉

2021-09-23 08:55 UTC, JEuler commented on chopper/lib/src/base.dart
> +  /// Utitlity method to shrink duplicated code (interceptors processing)
Fixed!

2021-10-10 06:20 UTC, merged

2021-11-08 08:48 UTC, stlr00 commented
When it will be at pub.dev?