Configurable HttpLoggingInterceptor
lejard-h/chopper pull request #399
Opened 2023-01-04 09:23 UTC by Guldem

Updated the `HttpLoggingInterceptor` so users can specify a more fine grained logging level for there needs.

Inspired by the `HttpLoggingInterceptor` configuration of OkHttp.

2023-01-05 18:39 UTC, techouse requested changes

2023-01-05 18:39 UTC, techouse commented on chopper/lib/src/http_logging_interceptor.dart
> +    if (base is http.Request) {
You could join the `if` conditions to something like
```dart
if (base is http.Request) {
  if (base.body.isNotEmpty) {
    bodyMessage = base.body;

    if (!_logHeaders) {
      startRequestMessage += ' (${base.bodyBytes.length}-byte body)';
    }
  }
}
```

2023-01-06 08:31 UTC, techouse approved these changes
LGTM

2023-01-06 15:24 UTC, JEuler approved these changes
Cool, many thanks!

2023-01-06 15:25 UTC, merged